version: '3.8'
services:
  db:
    container_name: tasks-db-container
    image: mysql
    env_file: .env
    tty: true
    restart: always
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    ports:
      - '3306:3306'
  api:
    container_name: todo-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/srv/app
    depends_on:
      - db
    environment:
      MYSQL_HOST: 'mysql'
    ports:
      - '3001:3001'
